# Generated by Django 4.2 on 2023-04-26 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('my_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.1))),
                ('brokerage', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.1))),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.investor')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_wallet.stock')),
            ],
        ),
    ]
