# Generated by Django 4.2 on 2023-04-26 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0003_alter_transaction_brokerage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='brokerage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unit_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
