# Generated by Django 4.2 on 2023-05-02 11:26

from django.db import migrations, models
import my_wallet.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0006_alter_transaction_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=6, unique=True, validators=[my_wallet.validators.validate_stock_code]),
        ),
    ]
