# Generated by Django 4.2 on 2023-04-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_investor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='risk_profile',
            field=models.CharField(choices=[('Conservador', 'conservador'), ('Moderado', 'moderado'), ('Arrojado', 'arrojado')], max_length=20),
        ),
    ]
