# Generated by Django 4.2 on 2023-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_investor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='risk_profile',
            field=models.CharField(choices=[('Conservador', 'Conservador'), ('Moderado', 'Moderado'), ('Arrojado', 'Arrojado')], max_length=20),
        ),
    ]
